import type { DemoComment, DemoOrder, DemoProject, NewOrderInput, SyncStatus } from "../hooks/use-shared-demo-state";
export type { DemoComment, DemoOrder, DemoProject, NewOrderInput, SyncStatus };
export type Screen = "dashboard" | "orders" | "order";
export type QueueMode = 'orders' | 'kanban';
export type Role = "owner" | "artist" | "printer" | "sewer" | "heatpress" | "qc" | "release";
export type User = { id: string; name: string; role: Role; initials: string; dept: string | null };
export type OrderRow = { ref: string; title: string; customer: string; due: string; stage: string; status: string; priority: string };
export type DashboardStats = { overdue: number; dueToday: number; waiting: number; qcIssues: number; ready: number; activeOrders: number; released: number };
export type PrototypeProps = {
  user: User; canCreateOrder: boolean; screen: Screen; queueMode: QueueMode;
  stage: string; qcStatus: 'Pending' | 'Passed' | 'Issue'; notice: string;
  currentOrder?: DemoOrder; lineUpItems: DemoProject[];
  orderRows: OrderRow[]; stats: DashboardStats;
  href: (screen: Screen, mode?: QueueMode) => string; setQueueMode: (mode: QueueMode) => void;
  openNewOrder: () => void; advanceStage: () => void; passQc: () => void;
  openRework: () => void; openUserSwitcher: () => void;
  openAddProject: (columns: string[]) => void;
  updateOrder: (orderId: string, patch: Partial<DemoOrder>) => void;
  removeItem: (orderId: string, projectId: string) => void;
  moveItemTo: (orderId: string, projectId: string, toIndex: number) => void;
  categories: string[]; orderTypes: Record<string, string[]>;
  lineUpTemplates: Record<string, string[]>;
  saveLineUpTemplate: (name: string, columns: string[], orderId?: string) => void;
  orderAccessDenied: boolean;
  syncStatus: SyncStatus;
  orderHref: (orderRef: string) => string;
};